# Generated by Django 6.0.3 on 2026-03-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='opcao_escolhida',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1, verbose_name='Opção Escolhida'),
        ),
    ]
