# Generated by Django 6.0.3 on 2026-04-04 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
        ('simulados', '0002_alter_simulado_data_fim_alter_simulado_questoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultado',
            name='tentativa',
            field=models.PositiveIntegerField(default=1, verbose_name='Tentativa'),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('aluno', 'simulado', 'tentativa')},
        ),
    ]
