# Generated by Django 6.0.3 on 2026-03-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('opcao_a', models.CharField(max_length=300, verbose_name='Alternativa A')),
                ('opcao_b', models.CharField(max_length=300, verbose_name='Alternativa B')),
                ('opcao_c', models.CharField(max_length=300, verbose_name='Alternativa C')),
                ('opcao_d', models.CharField(max_length=300, verbose_name='Alternativa D')),
                ('resposta_correta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], max_length=1, verbose_name='Resposta Correta')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='simulados.simulado', verbose_name='Simulado')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['simulado', 'ordem'],
            },
        ),
    ]
