# Generated by Django 6.0.3 on 2026-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem_enunciado',
            field=models.URLField(blank=True, help_text='Cole a URL de uma imagem para ilustrar o enunciado (opcional)', null=True, verbose_name='Imagem do Enunciado (URL)'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem_opcao_a',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem Alternativa A (URL)'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem_opcao_b',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem Alternativa B (URL)'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem_opcao_c',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem Alternativa C (URL)'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem_opcao_d',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem Alternativa D (URL)'),
        ),
    ]
