# Generated by Django 6.0.3 on 2026-03-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
        ('questoes', '0002_questao_imagem_enunciado_questao_imagem_opcao_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='M', max_length=1, verbose_name='Dificuldade'),
        ),
        migrations.AddField(
            model_name='questao',
            name='explicacao',
            field=models.TextField(blank=True, verbose_name='Explicação do gabarito'),
        ),
        migrations.AddField(
            model_name='questao',
            name='imagem_opcao_e',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem Alternativa E (URL)'),
        ),
        migrations.AddField(
            model_name='questao',
            name='opcao_e',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Alternativa E'),
        ),
        migrations.AddField(
            model_name='questao',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='conteudo.tema', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_a',
            field=models.CharField(max_length=500, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_b',
            field=models.CharField(max_length=500, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_c',
            field=models.CharField(max_length=500, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='opcao_d',
            field=models.CharField(max_length=500, verbose_name='Alternativa D'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta_correta',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], max_length=1, verbose_name='Resposta Correta'),
        ),
    ]
