# Generated by Django 6.0.3 on 2026-04-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0001_initial'),
        ('questoes', '0002_questao_revisado_alter_questao_imagem_opcao_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='importacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questoes_publicadas', to='importador.importacaoprova', verbose_name='Importação de Origem'),
        ),
        migrations.AddField(
            model_name='questao',
            name='numero_na_prova',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número na Prova'),
        ),
        migrations.AddField(
            model_name='questao',
            name='prova_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questoes_publicadas', to='importador.provaoriginal', verbose_name='Prova Original'),
        ),
    ]
