# Generated by Django 6.0.3 on 2026-04-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(choices=[('enem', 'ENEM')], default='enem', max_length=20, verbose_name='Tipo de exame')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Dia 1'), (2, 'Dia 2')], verbose_name='Dia')),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('rosa', 'Rosa'), ('cinza', 'Cinza')], max_length=20, verbose_name='Cor do caderno')),
                ('pdf_prova', models.FileField(upload_to='importacoes/provas/', verbose_name='PDF da prova')),
                ('pdf_gabarito', models.FileField(upload_to='importacoes/gabaritos/', verbose_name='PDF do gabarito')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('processando', 'Processando'), ('aguardando_revisao', 'Aguardando revisão'), ('parcialmente_publicada', 'Parcialmente publicada'), ('publicada', 'Publicada'), ('falhou', 'Falhou'), ('arquivada', 'Arquivada')], default='enviada', max_length=30, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_prova', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Importação de Prova',
                'verbose_name_plural': 'Importações de Prova',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProvaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('total_questoes_esperado', models.PositiveIntegerField(default=0, verbose_name='Total de questões esperado')),
                ('status_editorial', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisão'), ('parcial', 'Parcial'), ('completa', 'Completa')], default='em_revisao', max_length=20, verbose_name='Status editorial')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('importacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prova_original', to='importador.importacaoprova', verbose_name='Importação')),
            ],
            options={
                'verbose_name': 'Prova Original',
                'verbose_name_plural': 'Provas Originais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_na_prova', models.PositiveIntegerField(verbose_name='Número na prova')),
                ('texto_bruto', models.TextField(blank=True, verbose_name='Texto bruto extraído')),
                ('enunciado', models.TextField(blank=True, verbose_name='Enunciado')),
                ('opcao_a', models.TextField(blank=True, verbose_name='Alternativa A')),
                ('opcao_b', models.TextField(blank=True, verbose_name='Alternativa B')),
                ('opcao_c', models.TextField(blank=True, verbose_name='Alternativa C')),
                ('opcao_d', models.TextField(blank=True, verbose_name='Alternativa D')),
                ('opcao_e', models.TextField(blank=True, verbose_name='Alternativa E')),
                ('gabarito_oficial', models.CharField(blank=True, max_length=1, verbose_name='Gabarito oficial')),
                ('status', models.CharField(choices=[('pendente_aprovacao', 'Pendente de aprovação'), ('correcao_necessaria', 'Correção necessária'), ('rejeitada', 'Rejeitada'), ('publicada', 'Publicada')], default='pendente_aprovacao', max_length=30, verbose_name='Status')),
                ('motivo_status', models.TextField(blank=True, verbose_name='Motivo do status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_importadas', to='importador.importacaoprova', verbose_name='Importação')),
                ('prova_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_importadas', to='importador.provaoriginal', verbose_name='Prova original')),
            ],
            options={
                'verbose_name': 'Questão Importada',
                'verbose_name_plural': 'Questões Importadas',
                'ordering': ['numero_na_prova'],
                'unique_together': {('importacao', 'numero_na_prova')},
            },
        ),
    ]
