# Generated by Django 6.0.3 on 2026-04-04 00:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_questao_prova_original(apps, schema_editor):
    Questao = apps.get_model('questoes', 'Questao')
    QuestaoProvaOriginal = apps.get_model('importador', 'QuestaoProvaOriginal')

    for questao in Questao.objects.exclude(prova_original__isnull=True):
        QuestaoProvaOriginal.objects.get_or_create(
            questao_id=questao.id,
            prova_original_id=questao.prova_original_id,
            defaults={
                'numero_na_prova': questao.numero_na_prova or 0,
                'importacao_id': questao.importacao_origem_id or questao.prova_original.importacao_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0002_questaoimportada_questao_oficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoProvaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_na_prova', models.PositiveIntegerField(verbose_name='Numero na prova')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_questao', to='importador.importacaoprova', verbose_name='Importacao')),
                ('prova_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_questao', to='importador.provaoriginal', verbose_name='Prova original')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_prova', to='questoes.questao', verbose_name='Questao')),
            ],
            options={
                'verbose_name': 'Ocorrencia da Questao em Prova',
                'verbose_name_plural': 'Ocorrencias da Questao em Provas',
                'ordering': ['prova_original__importacao__ano', 'prova_original__importacao__dia', 'numero_na_prova'],
                'unique_together': {('questao', 'prova_original'), ('prova_original', 'numero_na_prova')},
            },
        ),
        migrations.RunPython(backfill_questao_prova_original, migrations.RunPython.noop),
    ]
