# Generated by Django 6.0.3 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0004_alter_questaoimportada_questao_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoimportada',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ingles', 'Ingles'), ('espanhol', 'Espanhol')], max_length=20, null=True, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='questaoprovaoriginal',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ingles', 'Ingles'), ('espanhol', 'Espanhol')], max_length=20, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterUniqueTogether(
            name='questaoimportada',
            unique_together={('importacao', 'numero_na_prova', 'idioma')},
        ),
        migrations.AlterUniqueTogether(
            name='questaoprovaoriginal',
            unique_together={('questao', 'prova_original', 'idioma'), ('prova_original', 'numero_na_prova', 'idioma')},
        ),
    ]
