# Generated by Django 6.0.3 on 2026-04-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_convite', models.CharField(blank=True, max_length=12, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='minhas_turmas', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_gerenciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
