# Generated by Django 6.0.3 on 2026-04-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0001_initial'),
        ('simulados', '0002_alter_simulado_data_fim_alter_simulado_questoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='eh_simulado_original',
            field=models.BooleanField(default=False, verbose_name='É Simulado Original'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='importacao_origem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulado_original', to='importador.importacaoprova', verbose_name='Importação de Origem'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='prova_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulados', to='importador.provaoriginal', verbose_name='Prova Original'),
        ),
    ]
